import { jsPDF } from "jspdf";
import rtos from "@/data/rto_addresses.json";
import type { Citizen } from "./storage";
import type { AuditReport } from "./validator";

export function generateContestLetter(opts: {
  citizen: Citizen;
  state: string;
  section: string;
  amount: number;
  date: string;
  challanNo?: string;
  grounds?: string;
  audit?: AuditReport;
}) {
  const rto = (rtos as Record<string, { state_name: string; rto_address: string; court: string }>)[opts.state];
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const M = 56;
  const W = doc.internal.pageSize.getWidth() - M * 2;
  let y = M;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("REPRESENTATION AGAINST TRAFFIC CHALLAN", M, y);
  y += 24;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Date: ${new Date().toLocaleDateString("en-IN")}`, M, y);
  y += 22;

  doc.setFont("helvetica", "bold");
  doc.text("To,", M, y); y += 14;
  doc.setFont("helvetica", "normal");
  const addr = rto?.rto_address ?? "The concerned Regional Transport Authority";
  doc.text(doc.splitTextToSize(addr, W), M, y); y += 38;

  doc.setFont("helvetica", "bold");
  doc.text(`Subject: Representation against challan dated ${new Date(opts.date).toLocaleDateString("en-IN")} under Section ${opts.section} of the Motor Vehicles Act, 1988.`, M, y, { maxWidth: W });
  y += 36;

  doc.setFont("helvetica", "normal");
  doc.text("Respected Sir / Madam,", M, y); y += 20;

  const body =
    `I, ${opts.citizen.name || "[Name]"}, residing at ${opts.citizen.address || "[Address]"}, ` +
    `phone ${opts.citizen.phone || "[Phone]"}, respectfully submit this representation in respect of ` +
    `challan${opts.challanNo ? " no. " + opts.challanNo : ""} issued under Section ${opts.section} of the ` +
    `Motor Vehicles Act, 1988, for an alleged fine of ₹${opts.amount}.\n\n` +
    `Grounds of representation:\n${opts.grounds || derivedGrounds(opts.audit)}\n\n` +
    `I therefore pray that the said challan be reviewed and set aside, or in the alternative, the matter be ` +
    `forwarded to the Hon'ble Court for adjudication. I undertake to appear and produce all relevant documents ` +
    `as and when required.\n\n` +
    `Yours sincerely,\n${opts.citizen.name || "[Name]"}`;

  const lines = doc.splitTextToSize(body, W);
  doc.text(lines, M, y);
  y += lines.length * 14 + 30;

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated by SARTHI — informational draft. Verify with ${rto?.court ?? "the local court"}.`, M, y);

  const id = `contest_${Date.now()}.pdf`;
  doc.save(id);
  return id;
}

function derivedGrounds(audit?: AuditReport): string {
  if (!audit) return "1. The challan is disputed on the merits and a proper hearing is requested.";
  const failed = Object.entries(audit.checks).filter(([, c]) => !c.pass);
  if (failed.length === 0) return "1. A proper hearing on merits is requested before any recovery is effected.";
  return failed.map(([k, c], i) => `${i + 1}. [${k.toUpperCase()}] ${c.note}`).join("\n");
}
