/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as SosRouteImport } from './routes/sos'
import { Route as MapRouteImport } from './routes/map'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/companion': typeof CompanionRoute
  '/contest': typeof ContestRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/sos': typeof SosRoute
  '/validator': typeof ValidatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/companion': typeof CompanionRoute
  '/contest': typeof ContestRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/sos': typeof SosRoute
  '/validator': typeof ValidatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/companion': typeof CompanionRoute
  '/contest': typeof ContestRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/sos': typeof SosRoute
  '/validator': typeof ValidatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/companion'
    | '/contest'
    | '/history'
    | '/map'
    | '/sos'
    | '/validator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/companion'
    | '/contest'
    | '/history'
    | '/map'
    | '/sos'
    | '/validator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/companion'
    | '/contest'
    | '/history'
    | '/map'
    | '/sos'
    | '/validator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  CompanionRoute: typeof CompanionRoute
  ContestRoute: typeof ContestRoute
  HistoryRoute: typeof HistoryRoute
  MapRoute: typeof MapRoute
  SosRoute: typeof SosRoute
  ValidatorRoute: typeof ValidatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  CompanionRoute: CompanionRoute,
  ContestRoute: ContestRoute,
  HistoryRoute: HistoryRoute,
  MapRoute: MapRoute,
  SosRoute: SosRoute,
  ValidatorRoute: ValidatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
